export const lightTheme = {
  overlay: "bg-black/80",
  overlayHome: "bg-black/30",
  cardBg: "bg-purple-900",
  cardBgTransparent: "bg-purple-900/70",
  titleText: "text-fuchsia-200",
  bodyText: "text-white",
  questionText: "text-sky-300",
  primaryButton: "bg-purple-800",
  optionButton: "bg-sky-500",
  tabBarBg: "#a21caf",
  tabBarActive: "#5001B6",
  tabBarInactive: "#3e2465",
  headerBg: "#7e22ce",
  navArrow: "#ffffff",
  navArrowLast: "#06b6d4",
  closeIcon: "#d4d4d8",
}

export const darkTheme = {
  overlay: "bg-slate-950/90",
  overlayHome: "bg-slate-950/60",
  cardBg: "bg-slate-800",
  cardBgTransparent: "bg-slate-800/70",
  titleText: "text-violet-300",
  bodyText: "text-slate-100",
  questionText: "text-cyan-300",
  primaryButton: "bg-indigo-800",
  optionButton: "bg-blue-700",
  tabBarBg: "#1e1b4b",
  tabBarActive: "#7c3aed",
  tabBarInactive: "#4338ca",
  headerBg: "#1e1b4b",
  navArrow: "#c4b5fd",
  navArrowLast: "#22d3ee",
  closeIcon: "#a78bfa",
}
